name: talker_http_logger
description: Lightweight and customizable http client logger on talker base
version: 0.1.0-dev.2
homepage: https://github.com/Frezyx/talker
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  http_interceptor: ^2.0.0-beta.7
  talker: ^4.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
